# 서버 포트 설정
server:
  port: 8082

tomcat:
  ajp:
    protocol: AJP/1.3
    port: 9091
    enabled: true

# database 연동 설정
spring:
  profiles:
    include:
      - oauth
      - db
  main:
    allow-bean-definition-overriding: true

# 게시판 이미지 파일 저장 경로 설정
file:
  path: "/src/main/resources/static/images/"